---
name: Build Main

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: tag Commit
        run: cd ${{ github.workspace }} && make git-tag
      - name: Run Makefile
        run: cd ${{ github.workspace }} && make docker-release
